### PR TITLE
Don't deplo kolla services on storage group

### PR DESCRIPTION
**Pull request by jovial**
We are managing the storage externally

### CODE REVIEW

**Review by oneswig — APPROVED** [review]
LGTM.  Remember to remove references to storage-ceph group

**Comment by jovial** [comment]
I'm getting this:
```
Attempted to read "/home/stackhpc/kayobe-env/src/kayobe-config/etc/kolla/inventory/overcloud" as ini file: /home/stackhpc/kayobe-env/src/kayobe-config/etc/kolla/inventory/overcloud:65: Section [baremetal:children] includes undefined group: storage 
```
with the above change.

**Review by markgoddard — COMMENTED** [review]
You need Kayobe commit 22c155349f8b45cea6eaa655ae52116630959c7c.

**Comment by jovial** [comment]
stackhpc/kayobe#169 now merged

**Pull request merged**
